/* ============ English ============
   The English texts. Mechanism lives in lang.js; keys here must match lang-ru.js
   exactly (a test checks that).

   This is not a translation of the Russian strings, it is the same game written
   in English: phrasing, word order and number forms are chosen for English and
   nothing is glued together from Russian sentence skeletons (see principle 4 in
   docs/PRINCIPLES.md — the rule that made us write it this way in the first place).

   Terminology, fixed once so it stays consistent everywhere:
     трюм = hold, место = slot, ведомость = ledger, разрыв цен = spread,
     контора = trading house, фрахт = freight, простой = idle day,
     предписание гильдии = guild order, надбавка = premium, ревизия = audit,
     скоропорт = perishable, оценщик = appraiser, барыга = fence,
     перекупщик = dealer, обязательство = commitment. */
const EN={
lng:'English',

money:v=>(v<0?'−$':'$')+Math.abs(Math.round(v)).toLocaleString('en-US'),
num:v=>Math.round(v).toLocaleString('en-US'),
pct:v=>Math.round(v)+'%',
dec:(v,n)=>v.toFixed(n),
// two forms instead of three; same signature so shared code does not care
plur:(n,one,few,many)=>Math.abs(Math.round(n))===1?one:(many||few),
slots:n=>EN.plur(n,'slot','slots'),
units:n=>EN.plur(n,'unit','units'),
unitsAcc:n=>EN.plur(n,'unit','units'),
days:n=>EN.plur(n,'day','days'),
ed:'units',
per:' ea.',
inDays:d=>{const n=d-S.day;return n<=0?'today':n===1?'tomorrow':'in '+n+' days'},
daysLeft:d=>{const n=d-S.day;return n<=0?'last day':n+' '+EN.days(n)+' left'},

goods:{sol:'Salt',zer:'Grain',tkn:'Cloth',kzh:'Leather',tab:'Tobacco',kof:'Coffee',chai:'Tea',pry:'Spices',
  kan:'Rope',stk:'Glass',zhl:'Iron',svn:'Lead',oln:'Tin',med:'Copper',
  sig:'Cigars',vsk:'Whisky',chs:'Clocks',lad:'Incense',srb:'Silver',zhm:'Pearls'},
mkts:{'Соляные ряды':'Salt Rows','Старый порт':'Old Harbour','Верхний рынок':'Upper Market',
  'Таможня':'Customs House','Дальняя фактория':'Far Outpost'},

ui:{
  title:'The Debt Ledger',
  house:'the Windmill trading house',
  day:'Day',cash:'Cash',hold:'Hold',rate:'Rate',reserve:'Reserve',
  chartPrices:'Prices',chartBalance:'Balance',
  byObservations:'what you have seen yourself',
  ledger:'Ledger',
  colGood:'Goods',colBuy:'Buy',colSell:'Sell',colHold:'In hold',colQty:'Qty',colDeal:'Deal',
  dutySec:'Guild order',contracts:'Contracts',records:'Records',rumours:'Word on the street',
  creditor:'Creditor',debt:'Debt',sumHint:'amount',repay:'Pay in',borrow:'Borrow',
  closeBook:'Close the book early',
  office:'Counting house',roads:'Roads',youHere:'you are here',
  logBtn:'Log',settingsBtn:'⚙ Settings',menuBtn:'Menu',
  build:'build',actions:'actions',inFocus:'in focus',
  rotateTitle:'Turn your phone upright',
  rotateText:'The Debt Ledger is played standing up — that is how ledgers are kept.',
  perDay:'%/day',
  counter:(acts,focus,total)=>acts+' actions · '+focus+'s in focus of '+total+'s'
},

diff:{
  easy:{n:'Apprentice',d:'45 days, $15,000 debt, 1.2% a day. Three markets, four goods. One purchase takes at most half the hold. Every rumour comes with how reliable it is.'},
  norm:{n:'Clerk',d:'30 days, $20,000 debt, 2% a day. Five markets, six goods, and guild orders you cannot refuse. A third of the rumours are lies. Contracts pay 10% better than at Apprentice.'},
  hard:{n:'Usurer',d:'24 days, $26,000 debt, 2.8% a day and rising. No hints about other markets or rumours, no limit on how deep you dig yourself in, guild orders come often. In exchange the pay is 30% better, premiums are higher and last a day longer.'},
  tut:{n:'Tutorial',d:'Tutorial'}
},

menu:{
  lede:'You inherited the trading house together with its debt.<br>Interest runs faster than careful trade.<br>One run takes 20–50 minutes.',
  newGame:'Start a new run',
  resume:'Continue the run',
  resumeLine:(pr,day,days)=>pr+' · day '+day+' of '+days,
  resumeMoney:(debt,cash,mkt)=>'debt '+money(debt)+' · cash '+money(cash)+' · '+mname(mkt),
  locked:prev=>'Locked. Opens once you close the book on '+prev+'.',
  confirmNew:(name,cur,day)=>'Start a new run on '+name+'? The current run ('+cur+', day '+day+') will be lost.',
  confirmYes:'Yes, start over',confirmNo:'Cancel',
  toTop:'↑ Back to the top',
  tut:'Tutorial',
  tutNew:'One mechanic at a time, and you try each one yourself. Takes about ten minutes.',
  tutDone:(a,b)=>'One mechanic at a time, and you try each one yourself. '+a+' of '+b+' done.'
},

set:{
  title:'Settings',
  sound:on=>'Sound: '+(on?'on':'off'),
  lang:'Language: English',
  close:'Close',
  achTitle:(got,all)=>'Achievements · '+got+' of '+all,
  offAll:'Turn all off',onAll:'Turn all on',
  off:'Turn off',on:'Turn on',
  opened:'unlocked',locked:'Not unlocked yet',hidden:'? ? ?'
},

hdr:{
  tomorrow:(sum,left)=>'Tomorrow adds '+money(sum)+'. '+left+' '+EN.days(left)+' left.',
  revision:(when,lim)=>' Audit '+when+': the debt must be down to '+money(lim)+
    '. Pass it and a new good opens up and the rate drops. Fail it and you get a fine plus perishables forced on you.',
  readyToClose:'Debt cleared, reserve saved up — you can close the book right now with “Close the book early”.',
  needReserve:left=>'Debt cleared. The reserve is still '+money(left)+' short — reach it and the book can be closed as a real win.',
  callNote:sum=>'Above '+money(sum)+' of debt the house is taken away.',
  cashEmpty:'The till is empty. Freight and fees will still be charged — straight into the debt. Better to borrow deliberately, and your own amount.',
  cashLow:'The till is running out. A little further and expenses start going into the debt without you deciding anything.'
},

tbl:{
  dayAndSpread:(day,spread)=>'day '+day+' · spread '+spread+'%',
  note:(list,lot)=>'Prices are per unit. Bulk differs: '+list+'. One purchase can take at most '+lot+' '+EN.slots(lot)+'.',
  noteItem:(name,bulk)=>name+' — '+bulk+' '+EN.slots(bulk)+' per unit',
  bulkPer:bulk=>bulk+' '+EN.slots(bulk)+' per unit',
  tagElite:'luxury',tagRot:'perishable',tagStd:'keeps well',
  noTrade:'not traded',onlyDealer:'dealer only',
  fakeRisk:'suspiciously cheap — may be counterfeit, at your own risk',
  cheaper:'cheaper than usual',
  pushedDown:p=>'you pushed the price down '+p+'%',
  pushedUp:p=>'you pushed the price up '+p+'%',
  boost:'premium ',penalty:'penalty ',
  forever:'for good',more:d=>d+' more days',
  holdLead:(q,avg)=>q+' '+EN.units(q)+' · '+money(avg)+' ea.',
  holdSub:(sum,places)=>money(sum)+' · '+places+' '+EN.slots(places),
  lot:(q,age)=>q+' '+EN.units(q)+' '+(age?'('+age+'d old)':'(fresh)'),
  fakesFound:n=>'counterfeits: '+n,
  exposed:(n,price)=>n+' exposed as fake — no honest market will take them. ',
  disposeBtn:price=>'Sell to a fence at '+money(price)+' ea.',
  buy:'Buy',lotBtn:'Batch',sell:'Sell',all:'All',
  dump:'Dump',dumpAll:'Dump all',
  deliver:n=>'Deliver on contract · '+n+' '+EN.units(n),
  deliverEmpty:'Awaited on contract — none in hold',
  none:'—',
  whyNoTrade:'not traded today',whyFull:'hold is full',whyPoor:'not enough cash',
  sellConfirm:(g,n)=>'A contract here pays more for '+g+'. Sell '+n+' '+EN.units(n)+' on the market instead?',
  sellAllConfirm:g=>'A contract here pays more for '+g+'. Sell it all on the market instead?'
},

road:{
  profile:(cheap,dear)=>'usually cheap: '+cheap+' · usually dear: '+dear,
  today:(lo,hi)=>'cheaper than usual today: '+lo+' · dearer: '+hi,
  dirLine:(mkt,cheap,dear)=>mkt+' — usually cheap '+cheap+', dear '+dear,
  dirNote:'“Usually” is the reputation of a market, not today\'s price. Today\'s you only see on the spot.',
  noDir:'Nobody keeps a market directory here. Remember it yourself.',
  go:mkt=>'Go → '+mkt,
  goLong:(d,f)=>d+' '+EN.days(d)+' across the desert · freight paid once, '+money(f),
  goHorses:f=>'a day across the desert (horses) · freight '+money(f),
  goPlain:f=>'a day on the road · freight '+money(f),
  goTent:mkt=>'Go → '+mkt+', stopping at the tent',
  goTentSub:d=>d+' '+EN.days(d)+' on the road · call on the bedouin',
  wait:'Wait out the day here',
  waitFee:f=>'storage fee '+money(f)
},

office:{
  upgrade:step=>'Enlarge the hold +'+step+' '+EN.slots(step),
  upgradeCost:(cost,full)=>money(cost)+(full?' · the hold is packed, good moment':''),
  upgradeMax:'The hold is as large as it gets',
  appraise:'Call the appraiser',
  appraiseCost:(cost,q)=>money(cost)+' · will check '+q+' '+EN.unitsAcc(q)+' of luxury goods for counterfeits',
  appraiseChecked:'the luxury goods in the hold are already checked',
  appraiseNothing:'nothing to check — only luxury goods are ever faked',
  insured:'The cargo is insured',
  insuredSub:(left,cover)=>'policy: '+left+' · covers '+money(cover)+' more',
  insure:'Insure the cargo',
  insureSub:(cost,days,back,sum)=>money(cost)+' · '+days+' moves, returns '+back+'% of losses'+
    (sum?' · insuring '+money(sum)+' of cargo':''),
  road:'Open the long road',
  roadSub:cost=>money(cost)+' · Salt Rows ↔ Far Outpost directly: two days on the road instead of three moves',
  horses:'Fast horses',
  horsesSub:cost=>money(cost)+' · the long road in a day instead of two, and past the desert without a stop',
  horsesDone:'Fast horses bought',horsesDoneSub:'the long road takes a day, not two',
  tar:'Tar barrels',
  tarSub:cost=>money(cost)+' · perishables in the hold stop going damp, for the rest of the run',
  tarDone:'Tar barrels bought',tarDoneSub:'perishables no longer go damp',
  boostsTitle:'Premiums in force',
  boostPerm:(g,v)=>g+': '+v+' on the selling price, for good',
  boostTemp:(g,v,d,duty)=>g+': '+v+' on the selling price, '+d+' more days'+(duty?' (failed guild order)':''),
  reliefLine:v=>'The rate is down by '+v+' points',
  tarLine:'Tar barrels: perishables in the hold stay dry',
  noBoosts:'No premiums. Closed contracts give them: an ordinary one temporarily, a golden one for good.'
},

msg:{
 noRoom:'Not enough cash, or not enough room in the hold.',
 bought:(g,n,sum)=>'Bought: '+g+' ×'+n+' for '+money(sum)+', at '+money(sum/n)+' each.',
 sold:(g,n,sum,pl,distress)=>(distress?'Dumped on a dealer: ':'Sold: ')+g+' ×'+n+' for '+money(sum)+
   ', at '+money(sum/n)+' each. '+(pl>=0?'Profit ':'Loss ')+money(Math.abs(pl))+'.',
 fakeTitle:'COUNTERFEIT',
 fakeAtMarket:(g,n)=>g+': the buyer\'s appraiser rejected '+n+' '+EN.units(n)+' as counterfeit and handed them back — no honest market will take them now.',
 fakeAtContract:(g,n)=>g+': the receiver rejected '+n+' '+EN.units(n)+' as counterfeit and handed them back — no honest receiver will take those crates now.',
 repaid:sum=>'Paid to the creditor: '+money(sum)+'.',
 debtClearTitle:'DEBT CLEARED',debtClear:'The debt is paid off in full.',
 borrowed:sum=>'Borrowed another '+money(sum)+'.',
 borrowForced:(sum,why)=>'The till was '+money(sum)+' short — it went into the debt: '+why+'.',
 upgraded:(cap,cost)=>'The hold now holds '+cap+' '+EN.slots(cap)+'. Paid '+money(cost)+'.',
 insured:(sum,left,prem)=>'Cargo insured for '+money(sum)+': the policy has '+left+'. Premium '+money(prem)+
   '. It covers what is in the hold right now — anything bought on top of that is not covered.',
 insPay:(sum,why,done)=>'The insurer paid out '+money(sum)+' for '+why+'.'+
   (done?' The policy is used up — it will not pay out again.':''),
 tarTitle:'TAR BARRELS',
 tarBought:cost=>'Tar barrels bought for '+money(cost)+'. Perishables in the hold stop going damp.',
 roadTitle:'THE LONG ROAD IS OPEN',
 roadBought:cost=>'The guide took '+money(cost)+'. Salt Rows and the Far Outpost are now linked directly: '+
   'two days on the road instead of three moves — but through the desert, where nobody trades and anything can happen.',
 horsesTitle:'FAST HORSES',
 horsesBought:cost=>'Bought for '+money(cost)+'. The long road now takes a day instead of two, and the desert goes by without a stop.',
 apDone:(cost,found)=>'The appraiser went through the hold for '+money(cost)+'. Counterfeits found: '+found+'.'+
   (found?' They have been set aside — no honest market or receiver will take them.':''),
 apFoundTitle:n=>'COUNTERFEITS FOUND: '+n,
 apFoundSub:'set aside — no honest market or receiver will take them',
 apCleanTitle:'NO COUNTERFEITS',
 apCleanSub:cost=>'the hold is clean · the inspection cost '+money(cost),
 disposed:(g,n,sum)=>'Sold the exposed fakes to a fence: '+g+' ×'+n+' for '+money(sum)+'.',
 yesSell:'Yes, sell on the market',noSell:'Cancel, I will deliver it',leave:'Ride on'
},

tier:{'мелкий':'small','средний':'medium','крупный':'large','золотой':'golden','предписание':'guild order'},
con:{
 goldTitle:'GOLDEN CONTRACT',
 goldOffer:(g,q,mkt)=>'A golden contract has come up: '+g+' ×'+q+' to '+mkt+'. Close it and the premium is permanent.',
 accepted:(g,q,mkt,when)=>'Contract taken: '+g+' ×'+q+'. Deliver to '+mkt+', due '+when+'.',
 got:sum=>'Received '+money(sum)+'.',
 gotPart:(last,total)=>'Received '+money(last)+' for the last batch, '+money(total)+' on the contract in all.',
 goldDoneTitle:'GOLDEN CONTRACT CLOSED',
 goldDone:(gotTxt,pct,g)=>'Golden contract closed. '+gotTxt+' A permanent +'+pct+'% on the selling price of '+g+', for good.',
 goldDoneAgain:gotTxt=>'Golden contract closed. '+gotTxt+' This good already carries its permanent premium.',
 dutyDoneTitle:'GUILD ORDER CLOSED',
 dutyDone:gotTxt=>'The guild order is closed. '+gotTxt+' The guild has no complaints.',
 doneTitle:'CONTRACT CLOSED',
 done:(gotTxt,pct,g,days)=>'Contract closed. '+gotTxt+' A +'+pct+'% premium on the selling price of '+g+' for '+days+' '+EN.days(days)+'.',
 partial:(ok,done,qty,paid,got,pay)=>'Delivered '+ok+' '+EN.units(ok)+', '+done+' of '+qty+' in all. Received '+money(paid)+
   ', '+money(got)+' of '+money(pay)+' on the contract so far.',
 declinedTitle:'CONTRACT DROPPED',
 declined:(g,fine)=>'Contract dropped: '+g+'. The remaining penalty of '+money(fine)+' goes into the debt.',
 declinedOffer:g=>'Offer turned down: '+g+'.',
 needMore:n=>'<b>'+n+'</b> more '+EN.units(n)+' to deliver',
 need:n=>'<b>'+n+'</b> '+EN.units(n)+' needed',
 inHold:n=>'in hold '+n,
 leftDays:(txt,col)=>'<b style="color:'+col+'">'+txt+'</b> left',
 termDays:(txt,grab)=>'due in '+txt+' · can be taken for '+grab+' more days',
 perUnit:'per unit',
 totalLine:(pay,extra,pen,live)=>money(pay)+' in all · '+extra+' · penalty '+(live?'up to ':'')+money(pen),
 boostGold:pct=>'+'+pct+'% on the selling price, for good',
 boostNone:'no premium',
 boostTemp:(pct,days)=>'+'+pct+'% premium for '+days+' '+EN.days(days),
 dutyRate:v=>' and +'+v+' points on the rate for the rest of the run',
 deliverN:n=>'Deliver '+n+' '+EN.units(n),
 deliverAt:mkt=>'Deliver at '+mkt,
 nothingToDeliver:'None in hold',
 take:'Take it',takeHere:'Cannot be taken here',
 takeHereWhy:'The delivery market is the one you are standing in — that contract would need no hauling at all',
 refuse:'Turn down',
 refuseLive:(g,fine)=>'Drop the contract for '+g+'? A penalty of '+money(fine)+' goes into the debt.',
 refuseOffer:g=>'Turn down the offer for '+g+'? It costs nothing, but the freed slot will not fill by itself — '+
   'a new offer comes with the next move.',
 refuseYes:'Yes, drop it',refuseNo:'Cancel'
},

w:{
 disTitle:'DISASTER',
 rats:(q,g)=>'Rats got into the hold and spoiled '+q+' '+EN.units(q)+' of '+g+'.',
 fire:(n,what)=>'Fire broke out in the warehouse — '+n+' '+EN.units(n)+' of cargo burned: '+what+'.',
 cart:(q,g)=>'The cart went over on the ruts — '+q+' '+EN.units(q)+' of '+g+' lost on the road.',
 customs:(q,g)=>'Customs confiscated '+q+' '+EN.units(q)+' of '+g+' — no explanation given.',
 lostSum:v=>' That is '+money(v)+' at cost.',
 notCovered:' Confiscation is not covered — no policy takes that case.',
 insBack:(back,net,done)=>' The insurer paid out '+money(back)+', net loss '+money(net)+'.'+
   (done?' The policy is used up.':''),
 wouldPay:v=>' With a policy you would have got '+money(v)+' back.',
 customsNoIns:'Insurance does not cover confiscation — customs does not ask permission.',
 disKind:{rats:'rats',fire:'fire',cart:'cart',customs:'customs'},
 lossWhy:'lost cargo',rotWhy:'spoiled cargo',fakeWhy:'a counterfeit',bribeWhy:'paying off the official',
 loreWhy:'price records',blindWhy:'a blind batch',
 bribeWhat:(n,name,cost)=>n+' '+EN.units(n)+' of '+name+' worth '+money(cost)+' at cost',
 bribeWhyDuty:'The goods are owed on a guild order — the official knows it and asks triple.',
 bribeWhyCon:'The goods are promised on a contract — the official knows you cannot lose them.',
 bribeWhyFree:'Free cargo: paying him off costs less than the loss itself.',
 bribeAsk:(what,why,price,short)=>'Customs took '+what+'. '+why+' Settle it for '+money(price)+'?'+
   (short?' The till is '+money(short)+' short — that part goes into the debt.':''),
 bribeYes:(price,short)=>'Settle for '+money(price)+(short?' (on debt)':''),
 bribeNo:'Refuse, let the cargo go',
 bribePaid:price=>'The official took '+money(price)+' — the cargo is back in the hold.',
 rateUpTitle:'THE RATE WENT UP',
 rateUp:v=>'The creditor raised the rate to '+v+'% a day.',
 interest:v=>'Interest: '+money(v),
 callTitle:'THE CREDITOR IS AT THE DOOR',
 callWarn:(debt,call,left,tomorrow)=>'Debt '+money(debt)+' against a line of '+money(call)+
   ' — '+money(left)+' before the house is taken. Reach the line and they take it that same day, deadline or not.'+
   (tomorrow?' Tomorrow\'s interest alone ('+money(tomorrow)+') is enough for that.':''),
 callBrief:(debt,call,left)=>'Debt '+money(debt)+' against a line of '+money(call)+' — '+money(left)+' before the house is taken.',
 revTomorrow:'AUDIT TOMORROW',
 revInDays:n=>'AUDIT IN '+n+' DAYS',
 revEnough:(have,need)=>'You hold '+money(have)+' in cash and goods — enough: the audit needs '+money(need)+' paid in.',
 revShort:(have,need,gap)=>'You hold '+money(have)+' in cash and goods, and '+money(need)+
   ' must be paid in — '+money(gap)+' short. Trade and close contracts.',
 revOver:(debt,lim,verdict,deadly,fine,call)=>'Debt '+money(debt)+' is above the '+money(lim)+' the audit demands.<br>'+verdict+
   (deadly?'<br>The fine for failing it ('+money(fine)+') would push the debt past '+money(call)+' — the house would be taken that same day.':''),
 revUnder:(debt,lim)=>'Debt '+money(debt)+' is already under the '+money(lim)+' the audit demands — it will pass, unless you borrow again.',
 revNote:(when,debt,lim,verdict)=>'Audit '+when+', and the debt of '+money(debt)+' is above the '+money(lim)+' demanded. '+verdict,
 revFailTitle:'AUDIT FAILED',
 revFail:(was,lim,fine,add)=>'Debt '+money(was)+' against the '+money(lim)+' demanded. A fine of '+money(fine)+' goes into the debt.'+
   (add?' And perishable goods are forced on you: '+add+'.':''),
 revPassTitle:'AUDIT PASSED',
 revPass:add=>'The rate drops by 0.2 points.'+(add?' A new good opens up for trade: '+add+'.':''),
 rotNote:(g,n,val,back)=>g+': '+n+' '+EN.units(n)+' went damp in the hold, '+money(val)+' at cost.'+
   (back>0?' The insurer paid out '+money(back)+', net loss '+money(val-back)+'.':''),
 rotTitle:'THE CARGO WENT DAMP',
 rotToast:(val,what,back)=>money(val)+' lost at cost ('+what+').'+
   (back>0?'<br>The insurer paid out '+money(back)+', net loss '+money(val-back)+'.':'<br>No policy — nothing to claim.'),
 dutyFailTitle:'GUILD ORDER FAILED',
 dutyFail:(g,fine,rate,pct,days)=>'Guild order failed: '+g+'. A penalty of '+money(fine)+
   ' goes into the debt. The guild complained to your creditor — the rate is up '+rate+' points for the rest of the run. Your selling price for '+
   g+' drops '+pct+'% for '+days+' days.',
 conFailTitle:'CONTRACT FAILED',
 conFail:(g,mkt,fine)=>'Contract failed: '+g+', to be delivered at '+mkt+'. A penalty of '+money(fine)+' goes into the debt.',
 dutyTitle:'GUILD ORDER',
 dutyOffer:(g,q,mkt,when)=>'Guild order: '+g+' ×'+q+' to '+mkt+', due '+when+'. It cannot be refused.',
 dueTitle:'DEADLINES CLOSING IN',
 dueLine:(pre,g,done,qty,mkt,when)=>pre+g+' '+done+'/'+qty+' to '+mkt+' — due '+when,
 dutyPre:'Guild order: ',goldPre:'Golden: ',
 tailsTitle:'CLOSE YOUR COMMITMENTS FIRST',
 tails:list=>'The book cannot be closed while these are open: '+list+'. Deliver or drop them and it will close.',
 tailItem:(duty,g,done,qty,mkt)=>(duty?'guild order ':'')+g+' '+done+'/'+qty+' to '+mkt
},

w2:{
 startNote:days=>'The trading house is yours, and so is the debt. You have '+days+' days.',
 shortPay:sum=>'Not enough for the expenses — '+money(sum)+' went into the debt.',
 moved:(from,to,freight,days)=>'Moved: '+from+' → '+to+'. Freight '+money(freight)+', '+
   (days>1?days+' '+EN.days(days)+' on the road.':'a day on the road.'),
 waited:fee=>'Waited the day out on the spot. Storage fee '+money(fee)+'.',
 doomFine:(i,fine,after)=>'The audit is tomorrow. Interest ('+money(i)+') and the fine for failing it ('+money(fine)+
   ') will push the debt to '+money(after),
 doomPlain:(i,after)=>'Tomorrow\'s interest ('+money(i)+') will push the debt to '+money(after),
 doomTail:(call,cash,canPay,going)=>' against a line of '+money(call)+' — the house will be taken that same day. '+
   'The till holds '+money(cash)+(canPay?', and you can pay in right here':'')+'. '+
   (going?'Go anyway':'Wait anyway')+'?',
 doomYes:going=>going?'Yes, go anyway':'Yes, wait anyway',
 doomNo:'Cancel, I stay',
 noInsTitle:'THE CARGO IS NOT INSURED',
 noIns:(inv,back,cost)=>'There is '+money(inv)+' of goods in the hold and no policy. A disaster takes 10–40% of the cargo at once; '+
   'insurance would return '+back+'% of the loss and costs '+money(cost)+'. I will not mention it again.',
 waitDutyTitle:'A GUILD ORDER IS AWAITED HERE',
 waitDuty:list=>'A guild order is awaited here: '+list+'. It cannot be refused, and failing it puts a penalty into the debt.',
 waitGoldTitle:'A GOLDEN CONTRACT IS AWAITED HERE',
 waitGold:list=>'A golden contract is awaited here: '+list+'. Close it and the premium is permanent.',
 waitConTitle:'A DELIVERY IS AWAITED HERE',
 waitCon:list=>'A contract is awaited here: '+list+'.',
 stormTitle:'SANDSTORM',
 storm:(q,g,cost,back)=>'A storm caught you in the desert: '+q+' '+EN.units(q)+' of '+g+' went into the sand, '+
   money(cost)+' at cost.'+(back>0?' The insurer paid out '+money(back)+'.':' No policy — nothing to claim.'),
 stormKind:'sandstorm',stormWhy:'a loss in the desert',
 lostWayTitle:'OFF THE TRACK',
 lostWay:'The guide lost the trail — one more night spent in the desert. Another day on the road.',
 tentTitle:'A TENT IN THE DESERT',
 tent:'There is a tent by the well. The bedouin does not trade the way markets do: he has his own goods, and he names his own price.',
 tentLeave:'Ride on, taking nothing',
 onDebt:' · the till is empty, this goes into the debt',
 offJunk:(g,n)=>'Sell the exposed fakes: '+g+' ×'+n,
 offJunkSub:(per,total)=>money(per)+' each — '+money(total)+' in hand, a fence pays a third of that',
 offBlind:(g,n)=>'Take a batch unseen: '+g+' ×'+n,
 offBlindSub:(price,per,base)=>money(price)+' — '+money(per)+' each against a base of '+money(base)+
   '. What is in the crates, the bedouin will not say',
 offLore:g=>'Buy price records: '+g,
 offLoreSub:cost=>money(cost)+' — prices on every market for every day so far, straight into your chart',
 bedJunk:(g,n,sum)=>'The bedouin took the exposed fakes: '+g+' ×'+n+' for '+money(sum)+'.',
 bedBlind:(g,n,price)=>'Took a batch from the bedouin unseen: '+g+' ×'+n+' for '+money(price)+
   '. What is inside, the appraiser or the buyer will show.',
 loreTitle:'RECORDS BOUGHT',
 bedLore:(g,n)=>'The bedouin handed over his records on '+g+': '+n+' price entries from every market went into your chart.',
 traderTitle:'A TRAVELLING TRADER',
 trader:'A man sits down beside you with a bundle of greasy sheets: prices from every market, day by day. He is selling.',
 traderLeave:'No need',
 traderOne:g=>'Price records: '+g,
 traderOneSub:cost=>money(cost)+' — every market, every day',
 traderAll:n=>'Take the lot ('+n+')',
 traderAllSub:(price,full)=>money(price)+' instead of '+money(full)+' — a third cheaper',
 traderGot:(g,n)=>'The travelling trader handed over his records on '+g+': '+n+' entries went into your chart.',
 traderGotAll:n=>'The travelling trader handed over everything he had: '+n+' price entries went into your charts.',
 blindWhy:'a batch from the bedouin',
 stampPaid:'SETTLED',stampBust:'BANKRUPT',stampTails:'LOOSE ENDS',stampNotReady:'NOT READY',
 rank1:'Legend of the trade rows',rank2:'Solid trader',rank3:'Barely balanced',
 endEarly:days=>'The book was closed '+days+' '+EN.days(days)+' ahead of the deadline.',
 endCall:'The creditor did not wait for the deadline.',
 endWin:'The book was closed on time, with enough put by for a fresh start.',
 endTails:'The debt is cleared and the reserve is there, but commitments were left unmet — the house was not handed over clean.',
 endNoReserve:'The debt is cleared, but nothing is left for a fresh start — no way to run a business.',
 endLose:'Time ran out and the debt is still there.'
},

fin:{
 trade:'Trade',bought:'Goods bought for',soldFor:'Goods sold for',profit:'Profit on trades',
 deals:'Trades (buy / sell)',cpay:'Earned on commitments',
 closed:'Commitments closed',failedN:n=>' ('+n+' failed)',
 debtBox:'Debt and creditor',interest:'Interest accrued',borrowed:'Borrowed from the creditor',
 repaid:'Paid to the creditor',fines:'Audit fines',pens:'Penalties for failures',
 audits:'Audits passed',ofN:(a,b)=>a+' of '+b,
 roadBox:'Road and hold',moves:'Moves / idle days',freight:'Freight and storage fees',
 upgrades:'Hold enlargements',noUpgrade:'never enlarged',
 mkts:'Markets visited',rot:'Spoiled in the hold',fakes:'Counterfeits uncovered',
 riskBox:'Risk',lost:'Lost to disasters',insBack:'Paid out by the insurer',
 serv:'Services (policies, appraiser, barrels)',bribes:'Settled with the official',
 bribesN:(n,sum)=>n+' '+EN.plur(n,'time','times')+' for '+sum,never:'never',
 peak:'Peak debt',nearest:'Closest to zero',
 day:d=>' · d'+d,
 memories:'What stayed with you',
 dealLine:(pre,g,q,mkt,sign,sum,d)=>pre+' <b>'+g+'</b> ×'+q+' at '+mkt+', '+sign+sum+' · d'+d,
 best:'Best trade:',worst:'Worst trade:',
 bigc:(g,q,tier,sum,d)=>'Biggest delivery: <b>'+g+'</b> ×'+q+' ('+tier+'), '+sum+' · d'+d,
 bigd:(kind,sum,d)=>'Costliest disaster: <b>'+kind+'</b>, −'+sum+' · d'+d,
 peakLine:(d,sum)=>'The debt was at its highest on d'+d+': '+sum,
 nearLine:(d,debt,have,left,plus)=>'Closest to zero on d'+d+': debt '+debt+' against '+have+
   ' in cash and goods — net '+(plus?'already '+left+' in the black':left+' still to pay'),
 noIns:'Never bought a policy for the whole run',
 distress:'Had to dump cargo on a dealer where the goods were not traded',
 noIdle:'Not a single idle day: every day was a move',
 verdict:(int,earned)=>'Interest ate '+int+'. Trade and commitments earned '+earned+'.',
 verdictShare:p=>' The creditor took '+p+'% of everything you made.',
 verdictTimes:x=>' That is '+x+' times more than you made: the debt grew faster than the trade.',
 verdictNone:' Trade never went into the black — the interest piled up on nothing.',
 head:(days,all)=>'Run so far · '+days+' of '+all+' days',
 headTime:(mins,acts)=>mins+' min of active play · '+acts+' actions',
 capital:sum=>'Capital: '+sum,debtLeft:sum=>'Debt remaining: '+sum,
 rank:r=>'Rank: '+r,unlocked:d=>'Difficulty unlocked: '+d,
 achOpened:list=>'Achievements unlocked: '+list,
 exportBtn:'Export the log',toMenu:'To the menu',
 reserveGot:(cash,left)=>'The reserve is there: '+cash+' with the debt cleared.'+left,
 reserveTails:list=>' But commitments are still open ('+list+') — the book closes once they are closed.',
 reserveFree:' You can close the book right now — or carry on and earn more.',
 reserveOk:'Understood',reserveClose:'Close the book',reserveGoOn:'Carry on playing'
},

ev:{
 urozhay:{hi:['Hail flattened the fields, the harvest is gone.','Drought: a third of the usual harvest.','The wagons never made it — the roads washed out.'],
          lo:['The harvest came in twice over.','Two extra wagon trains arrived from the fields.','The granaries are bursting, everything goes cheap.']},
 remeslo:{hi:['The craftsmen are on strike, the workshops stand idle.','Fire in the artisan quarter, the workshops burned.','No raw material came in, the shops have stopped.'],
          lo:['The workshops overfilled their order.','A workshop went under, everything must go.','A smuggled shipment collapsed the price.']},
 rudnik:{hi:['The mine is flooded, digging has stopped.','The foundry is buying up everything there is.','A cave-in at the shaft, no deliveries.'],
         lo:['The mine turned out double its quota.','The smelters have stopped, there is nowhere to put the metal.','A large shipment arrived from overseas.']},
 roskosh:{hi:['The court has a new fashion: the rich are buying it all.','A caravan of luxuries was plundered.','The guild is holding the goods back.']
          ,lo:['Rumours of counterfeits scared the buyers off.','An auction of seized goods collapsed the price.','The fashion passed, nobody wants it.']}
},
misc:{
 evLine:(mkt,flavour,g,up)=>mkt+'. '+flavour+' The price of '+g+' has '+(up?'shot up':'collapsed')+'.',
 rumHigh:(mkt,g,p)=>mkt+'. They pay well for '+g+' there — around '+money(p)+' a unit.',
 rumLow:(mkt,g,p)=>mkt+'. '+g+' goes cheap there — around '+money(p)+' a unit.',
 when:n=>n===1?'tomorrow':'in '+n+' days',
 tickEvent:'event',
 mapDays:d=>d+' '+EN.days(d),
 hasInHold:'You are carrying this good',
 noObs:'Nothing observed yet. A price is recorded on the day you stand in that market — so the chart grows as you travel.',
 avgBuy:'cost ',
 logDay:d=>'D'+d,
 achTitle:'ACHIEVEMENT',
 achLine:(n,b)=>'Achievement: '+n+'. '+b+'.'
},

tut:{
 cat:'Basics',
 head:{title:'Tutorial',
  lede:'One mechanic at a time, and you try each one yourself.<br>Any step can be repeated, and you can leave whenever you like.',
  done:(a,b)=>a+' of '+b+' done.',
  locked:prev=>'Opens once you finish “'+prev+'”.',
  passed:'done',back:'← Back to the menu',
  lessonDone:'Lesson finished',lessonNo:(i,n)=>'lesson '+i+' of '+n,
  stepNo:(i,n)=>'step '+i+' of '+n,
  next:'Next →',finish:'Finish the lesson',
  repeat:'Repeat the step',restart:'Restart the lesson',exit:'Leave',
  nextLesson:n=>'Next: “'+n+'”',again:'Do it again',toList:'Back to the lessons',
  ok:'Done.',
  stuck:'This step cannot be finished from here — there is no money left for it. No harm done: “Repeat the step” puts everything back to where the step began.',
  allDone:(n,b)=>'The whole tutorial is finished. Achievement unlocked: “'+n+'” — '+b+', in every run.'},
 o1:{n:'The debt grows by itself',one:'Interest accrues every day, even when you do nothing.',
  s:[{say:'The Creditor panel shows the debt, the rate and what tomorrow will add. Let us check: without buying anything, press “Wait out the day here”.',
      after:()=>{TUT.mem.i2=tst('int');return 'The debt grew by '+money(TUT.mem.i2-TUT.mem.i1)+'. You did absolutely nothing — and you already owe more.'}},
     {say:'One more day. Watch the interest: it will not be the same figure.',
      after:()=>'Today it added '+money(tst('int')-TUT.mem.i2)+' against '+money(TUT.mem.i2-TUT.mem.i1)+
        ' yesterday. Interest is charged on the interest too — the debt speeds itself up. In a real run the rate climbs towards the end as well.'},
     {say:'There is only one way to stop it — pay it down. The Creditor panel has a field for the amount: type any figure and press “Pay in”.',
      after:()=>'Paid in '+money(tst('repaid'))+'. A smaller debt means smaller interest tomorrow.'}],
  fin:'That is the whole game: money has to turn over faster than the interest accrues. Every day the till sits idle costs you interest. Next — how money turns over.'},
 o2:{n:'The spread',one:'Buying and selling in one market is always a loss.',
  s:[{say:()=>'Every good in the ledger has two prices: “Buy” at '+money(ask('kan'))+' and “Sell” at '+money(bid('kan'))+
        '. Same good, same place, same minute. Take some rope — as much as you like.',
      after:()=>'Bought for '+money(tst('bought'))+'. The money left the till and now sits in the hold as goods.'},
     {say:'Now sell it straight back, right here and right now. The “All” button in the same row.',
      after:()=>money(tst('sold'))+' came back. '+money(tst('bought')-tst('sold'))+' lost on nothing at all, in one minute.'}],
  fin:()=>'That is the spread. Here it is '+Math.round(spreadOf(S.mkt)*100)+
    '%, and every market has its own — it is written above the ledger, next to the day. Because of it you cannot earn by standing still: money is made by the difference between markets, not by buying.'},
 o3:{n:'Goods have to travel',one:'Money is made on the difference between markets, and a move costs a day and freight.',
  s:[{say:()=>'Salt Rows. Rope is cheap here: '+money(ask('kan'))+' a unit. Take a dozen: the quantity field already shows 1, press “+10” — it becomes 11 — and “Buy”.',
      after:()=>tq('kan')+' units in the hold, '+money(tst('bought'))+' spent.'},
     {say:'Old Harbour pays noticeably more for rope. It is the next market over — a day on the road. Press “Go → Old Harbour” in the Roads panel.',
      after:()=>'Freight '+money(tst('freight'))+' — the charge for hauling, and the heavier the hold the more it costs. And a day went by: interest '+money(tst('int'))+'.'},
     {say:()=>'Here they give '+money(bid('kan'))+' for them. Sell.',
      after:()=>money(tst('sold'))+' taken against '+money(tst('bought'))+' spent. After freight and interest, '+
        money(tst('sold')-tst('bought')-tst('freight')-tst('int'))+' clear.'}],
  fin:'That is the whole cycle: buy where it is cheap, haul it where it is dear, and get there before the interest eats the difference. Everything else in the game is about what gets in the way of that.'},
 o4:{n:'The hold is space, not money',one:'The hold is counted in slots, and it usually runs out before the money does.',
  s:[{say:'The header has a “Hold” counter: taken out of capacity. Salt takes one slot a unit. Take a batch of it — the “Batch” button in the Salt row.',
      after:()=>Math.round(held())+' of '+capacity()+' slots taken, and only '+money(tst('bought'))+
        ' left the till. Salt is cheap but bulky: little money, a lot of space.'},
     {say:'Sell all the salt — clear the hold.',
      after:()=>'The hold is empty again: '+Math.round(held())+' of '+capacity()+'.'},
     {say:'Now take three units of copper: the field already shows 1, press “+2” — it becomes 3 — and “Buy”.',
      after:()=>{const m=3*good('med').bulk;return 'Three units of copper take '+m+' '+mesto(m)+'. The same space holds '+m+' '+
        plural(m,'unit','units','units')+' of salt, and costs tens of times less.'}}],
  fin:'Space is the second resource after money, and it is the one that runs out first. Expensive goods pay better per slot — and ruin you faster if they do not sell. The hold can be enlarged for money in the Counting house.'},
 o5:{n:'A big trade moves the price',one:'The first part of a trade goes at the quoted price, after that the price turns against you.',
  s:[{say:()=>'Rope buys at '+money(ask('kan'))+' right now. Press “Batch”: it takes three quarters of what fits in the hold.',
      after:()=>'Took '+tq('kan')+' units at '+money(avg('kan'))+' on average. And “Buy” now shows '+money(ask('kan'))+
        ' instead of '+money(TUT.mem.a0)+': the market is not bottomless.'},
     {say:'Press “Batch” once more and watch the price.',
      after:()=>'The average in the hold went from '+money(TUT.mem.av)+' to '+money(avg('kan'))+
        '. The first few dozen slots a day do not move the price; after that every purchase lifts it. The market drifts back over a couple of days.'},
     {say:'Now sell it all at once — the “All” button.',
      after:()=>'Sold for '+money(tst('sold'))+' against '+money(tst('bought'))+' spent — '+
        (tst('profit')>=0?'profit ':'loss ')+money(Math.abs(tst('profit')))+
        '. Selling pushes the price the other way: from '+money(TUT.mem.b0)+' down to '+money(bid('kan'))+'.'}],
  fin:'So “fill the hold with one good” is never free: the bigger the trade, the worse the price. Splitting it across days and markets is a strategy too.'},
 o6:{n:'A commitment',one:'A contract is an order for goods in another town by a deadline, paid on delivery.',
  s:[{say:'The contract card says it all: what to haul, how much, where to and by when. It pays above the market, but only on delivery — and missing the deadline puts a penalty into your debt. Press “Take it”.',
      after:'Contract taken. Delivery is at Old Harbour: it is always somewhere you are not, and that is the whole point.'},
     {say:'Twenty units of rope are needed, and rope is cheap here. Buy it — “+10” twice gives 21, which is enough.',
      after:()=>tq('kan')+' units in the hold, '+money(tst('bought'))+' spent.'},
     {say:'Now haul it to Old Harbour.',after:'You have arrived. A “Deliver” button appeared on the contract card.'},
     {say:'Deliver it — the button on the contract card, or the one in the goods row of the ledger.',
      after:()=>'Received '+money(tst('cpay'))+'. The same rope on the market would have brought about '+money(bid('kan')*20)+
        ' — the difference is what you were paid for taking on the deadline and the road.'}],
  fin:'Contracts are the real money in this game: the market pays percentages, commitments pay multiples. There are always three to choose from, they can be delivered in parts, and a closed contract also lifts your selling price for that good for a few days.'},
 o7:{n:'How this is won',one:'Winning means the debt cleared, a reserve saved up and no loose ends.',
  s:[{say:()=>'The debt left is small, and the till holds '+money(S.cash)+'. Clear the debt in full: type the amount in the Creditor panel and press “Pay in”.',
      after:()=>'The debt is cleared. But the book is not closed yet — look at “Reserve” in the header: '+money(S.cash)+' of '+money(reserveTarget())+'.'},
     {say:'The reserve is the other half of the condition: after settling with the creditor the till must still hold at least 40% of the debt you started with. It is there — and a “Close the book early” button has appeared in the Creditor panel. Press it.',
      after:'The “SETTLED” stamp — that is the win.'}],
  fin:'There is a third condition too: closed commitments. You cannot leave the guild with undelivered cargo and call yourself the winner — such a run gets the “LOOSE ENDS” stamp instead. And the earlier the book is closed, the higher the rank at the end.'}
},

ach:{
 a1:{n:'First entry',d:'Make your first trade',b:'+1% on the selling price'},
 a2:{n:'Clean profit',d:'Make $1,500 on a single trade',b:'+1% on the selling price'},
 a3:{n:'Debt halved',d:'Cut the debt to half of what you started with',b:'−0.03 points off the rate'},
 a4:{n:'Book closed',d:'Win a run on any difficulty',b:'+2% on the selling price'},
 a5:{n:'Wholesaler',d:'Fill the whole hold with a single purchase',b:'−5% freight'},
 a6:{n:'Good eye',d:'Buy a risky batch without a single counterfeit in it',b:'−3 points of counterfeit risk'},
 a7:{n:'Inquiry',d:'Uncover 5 counterfeits in one run',b:'Appraiser 30% cheaper'},
 a8:{n:'Logistician',d:'Close 5 contracts in one run — one after another, not all at once',b:'+3% contract pay'},
 a9:{n:'Golden seal',d:'Close a golden contract',b:'+15 slots in the hold'},
 a10:{n:'Dry hold',d:'Keep perishables for 6 days without losing any',b:'−6% spoilage'},
 a11:{n:'Spite the usurer',d:'Clear the debt 5+ days before the deadline',b:'−0.03 points off the rate'},
 a12:{n:'Fat till',d:'Hold $15,000 in cash',b:'−3% spread'},
 a13:{n:'First delivery',d:'Close any contract',b:'+2% contract pay'},
 a14:{n:'Clerk conquered',d:'Win a run on Clerk',b:'+1% on the selling price'},
 a15:{n:'Usurer undone',d:'Win a run on Usurer',b:'−0.05 points off the rate'},
 a16:{n:'Every road walked',d:'Visit every market of the run in a single run',b:'−3% freight'},
 a17:{n:'Never idle',d:'Win without ever waiting out a day on the spot',b:'−3% freight'},
 a18:{n:'The auditor is pleased',d:'Fail no audit in a run',b:'−0.02 points off the rate'},
 a19:{n:'Uninsured',d:'Win without ever buying insurance',b:'−2% spread'},
 a20:{n:'On your own',d:'Win without ever hiring the appraiser',b:'Appraiser another 10% cheaper'},
 a21:{n:'On the edge',d:'End up with an empty till and carry on anyway',b:'−0.02 points off the rate'},
 a22:{n:'Ahead of schedule',d:'Close a contract 5+ days before it is due',b:'+2% contract pay'},
 a23:{n:'Cold blood',d:'Win without ever dumping goods on a dealer at a knock-down price',b:'+1% on the selling price'},
 a24:{n:'Cabinet of rarities',d:'Hold two or more luxury goods at the same time',b:'−2 points of counterfeit risk'},
 a26:{n:'The basics',d:'Finish the whole tutorial',b:'−2% spread'},
 a25:{n:'Without a single crutch',d:'Unlock every other achievement, turn them all off and win on Usurer',b:'+5% on the selling price and −5% on the buying price, unlocks the Skinflint difficulty'}
},

chart:{
  runProgress:'Run so far',balanceWord:'balance',
  balanceNote:'cash, goods and debt day by day',
  noRecords:'No records yet.',
  balanceTab:'Balance',
  keyDebt:v=>'debt '+money(v),
  keyCash:v=>'cash '+money(v),
  keyInv:v=>'in goods '+money(v)+' at cost',
  keyNet:v=>'┄ net '+money(v)+' — cash and goods minus debt',
  keyAudit:'┆ audit day and the debt it demands',
  keyCall:'┄ the line past which the house is taken',
  keyReserve:'┄ the reserve you cannot close the book without',
  axisAudit:'audit',
  axisCall:v=>'house taken · '+money(v),
  axisReserve:v=>'reserve for a fresh start · '+money(v),
  yourAvg:'┄ your average purchase',
  rumHint:'▲▽ price rumour, tap for detail · fades in 2 days',
  rumToast:d=>'RUMOUR · DAY '+d,
  dayTick:d=>'d'+d
},

rum:{
  quiet:'Quiet so far.',
  fresh:'new',
  head:(d,label)=>'D'+d+' · '+label,
  trusted:'confirmed',doubted:'unconfirmed rumour',plain:'rumour',
  inWork:n=>n+' in progress',
  noRefusal:'cannot be refused'
}
};
